import { Product } from '../types';

export const WALL_PANELS: Product[] = [
  {
    id: 'wall-panel-1-1',
    code: '1.1',
    legacyCode: 'OS_VF_01',
    name: 'Obvodový panel s kontaktním zateplením a armovací vrstvou',
    subtitle: 'Difuzně otevřená skladba s minerálním kontaktním zateplením 100 mm a vyztuženou armovací vrstvou.',
    category: 'WALL_OUTER',
    declaredThicknessMm: 341.0,
    unitPriceExVat: 8500.0,
    isRecommended: true,
    technicalParameters: {
      uValue: 0.14,
      rwDb: 52,
      fireResistance: 'REI 60 / DP1',
      massKgM2: 78.5,
    },
    electricalPreparation: {
      included: true,
      responsibility: 'supplier',
      heading: 'Příprava pro elektroinstalaci je součástí panelu',
      description: 'Panel obsahuje 40mm instalační předstěnu. V rozsahu schválené výrobní dokumentace jsou připraveny elektroinstalační chráničky (husí krky) a vývrty pro následné osazení elektroinstalačních krabic. Vedení je připraveno před parotěsnou rovinou, takže při dokončení elektroinstalace není nutné zasahovat do nosné konstrukce ani porušovat parozábranu.',
      includedItems: [
        'Elektroinstalační chráničky (husí krky)',
        'Vývrty pro následné osazení elektroinstalačních krabic ve 40mm předstěně',
      ],
      excludedItems: [
        'Elektroinstalační krabice',
        'Kabeláž',
        'Zásuvky, vypínače a další koncové přístroje',
        'Zapojení a kompletace',
        'Výchozí revize elektroinstalace',
      ],
    },
    deliveryScope: {
      included: [
        'Nosný rám KVH 60/160 mm s minerální izolací 160 mm',
        'Vnitřní oboustranné ztužující opláštění deskami Fermacell 12,5 mm',
        'Parotěsná rovina před nosnou konstrukcí',
        'Instalační předstěna 40 mm s minerální izolací',
        'Minerální fasádní zateplení 100 mm s podélnou orientací vláken',
        'Základní armovací stěrka 3 mm s výztužnou sklotextilní mřížkou (perlinkou)',
      ],
      excluded: [
        'Finální tmelení, stěrkování, penetrace a interiérová malba',
        'Penetrace a finální silikonová fasádní omítka',
      ],
      clientSupplied: [
        'Finální interiérové povrchové úpravy (tmelení Q2/Q3, výmalba)',
        'Fasádní penetrace a finální omítka na armovací vrstvu',
      ],
      deliveryNote: 'Součástí dodaného panelu nejsou finální povrchové úpravy na straně interiéru ani exteriéru. Interiér končí deskou Fermacell bez finálního tmelení, stěrkování, penetrace a malby. Exteriér končí armovací stěrkou s perlinkou bez penetrace a finální fasádní omítky.',
    },
    images: {
      assembledCutawayWebp: '/panels/catalog/1_1/panel_1_1_photoreal_assembled_cutaway.webp',
      explodedWebp: '/panels/catalog/1_1/panel_1_1_photoreal_exploded.webp',
      fullWebp: '/panels/catalog/1_1/panel_1_1_photoreal_full.webp',
      thumbnailWebp: '/panels/catalog/1_1/panel_1_1_thumb.webp',
      assembledCutawayPng: '/panels/catalog/1_1/panel_1_1_photoreal_assembled_cutaway.png',
      explodedPng: '/panels/catalog/1_1/panel_1_1_photoreal_exploded.png',
      reviewPng: '/panels/catalog/1_1/panel_1_1_photoreal_review.png',
    },
    layers: [
      { id: 'L01', order: 1, name: 'Sádrovláknitá deska Fermacell 12,5 mm', materialId: 'fermacell_raw', geometry: 'solid', thicknessMm: 12.5, additiveToTotal: true, explodedGroup: 0, massKgM2: 15.0, lambdaWMk: 0.32, fireClass: 'A2', function: 'Vnitřní opláštění a podklad pro finální povrchovou úpravu na stavbě.' },
      { id: 'L02', order: 2, name: 'Instalační předstěna z latí 60/40 mm', materialId: 'kvh_spruce', geometry: 'frame', thicknessMm: 40.0, additiveToTotal: true, explodedGroup: 1, massKgM2: 2.0, lambdaWMk: 0.18, fireClass: 'C3', function: 'Instalační prostor tloušťky 40 mm pro vedení rozvodů před parotěsnou rovinou.' },
      { id: 'L03', order: 3, name: 'Minerální izolace v instalační předstěně', materialId: 'mineral_wool_soft', geometry: 'hosted_infill', hostLayerId: 'L02', thicknessMm: 40.0, additiveToTotal: false, explodedGroup: 1, massKgM2: null, lambdaWMk: 0.035, fireClass: 'A1', function: 'Vyplnění instalační dutiny pro zlepšení tepelných a akustických vlastností.' },
      { id: 'L04', order: 4, name: 'Sádrovláknitá deska Fermacell 12,5 mm', materialId: 'fermacell_raw', geometry: 'solid', thicknessMm: 12.5, additiveToTotal: true, explodedGroup: 2, massKgM2: 15.0, lambdaWMk: 0.32, fireClass: 'A2', function: 'Ztužující opláštění před nosnou konstrukcí a podklad parotěsné roviny.' },
      { id: 'L05', order: 5, name: 'Parozábrana', materialId: 'vapour_membrane', geometry: 'solid', thicknessMm: 0.5, additiveToTotal: true, explodedGroup: 3, massKgM2: 1.0, lambdaWMk: null, fireClass: null, function: 'Omezení průniku vodní páry z interiéru do nosné části panelu.' },
      { id: 'L06', order: 6, name: 'Nosný rám KVH 60/160 mm', materialId: 'kvh_spruce', geometry: 'frame', thicknessMm: 160.0, additiveToTotal: true, explodedGroup: 4, massKgM2: 10.0, lambdaWMk: 0.18, fireClass: 'C3', function: 'Hlavní nosná dřevěná konstrukce obvodového panelu.' },
      { id: 'L07', order: 7, name: 'Minerální izolace v nosném rámu', materialId: 'mineral_wool_soft', geometry: 'hosted_infill', hostLayerId: 'L06', thicknessMm: 160.0, additiveToTotal: false, explodedGroup: 4, massKgM2: null, lambdaWMk: 0.035, fireClass: 'A1', function: 'Hlavní tepelněizolační výplň mezi sloupky nosného rámu.' },
      { id: 'L08', order: 8, name: 'Sádrovláknitá deska Fermacell 12,5 mm', materialId: 'fermacell_raw', geometry: 'solid', thicknessMm: 12.5, additiveToTotal: true, explodedGroup: 5, massKgM2: 15.0, lambdaWMk: 0.32, fireClass: 'A2', function: 'Vnější ztužující opláštění nosného rámu a podklad kontaktního zateplení.' },
      { id: 'L09', order: 9, name: 'Minerální fasádní tepelná izolace 100 mm', materialId: 'mineral_wool_facade', geometry: 'solid', thicknessMm: 100.0, additiveToTotal: true, explodedGroup: 6, massKgM2: 5.0, lambdaWMk: 0.035, fireClass: 'A1', function: 'Kontaktní zateplení omezující tepelné mosty rámové konstrukce.' },
      { id: 'L10', order: 10, name: 'Armovací stěrka s perlinkou 3 mm', materialId: 'reinforced_basecoat', geometry: 'solid', thicknessMm: 3.0, additiveToTotal: true, explodedGroup: 7, massKgM2: null, lambdaWMk: null, fireClass: 'dle systému', function: 'Základní vyztužená vrstva fasádního systému bez finální omítky.' },
    ],
  },
  {
    id: 'wall-panel-1-2',
    code: '1.2',
    legacyCode: 'OS_VF_02',
    name: 'Obvodový panel s přípravou pro provětrávanou dřevěnou fasádu',
    subtitle: 'Masivnější nosný rám 240 mm, difuzní fasádní membrána a dvojitý dřevěný podkladní rošt.',
    category: 'WALL_OUTER',
    declaredThicknessMm: 398.5,
    unitPriceExVat: 10238.0,
    technicalParameters: {
      uValue: 0.13,
      rwDb: 54,
      fireResistance: 'REI 60 / DP1',
      massKgM2: 82.0,
    },
    electricalPreparation: {
      included: true,
      responsibility: 'supplier',
      heading: 'Příprava pro elektroinstalaci je součástí panelu',
      description: 'Panel obsahuje 40mm instalační předstěnu. V rozsahu schválené výrobní dokumentace jsou připraveny elektroinstalační chráničky (husí krky) a vývrty pro následné osazení elektroinstalačních krabic. Vedení je připraveno před parotěsnou rovinou, takže při dokončení elektroinstalace není nutné zasahovat do nosné konstrukce ani porušovat parozábranu.',
      includedItems: [
        'Elektroinstalační chráničky (husí krky)',
        'Vývrty pro následné osazení elektroinstalačních krabic ve 40mm předstěně',
      ],
      excludedItems: [
        'Elektroinstalační krabice',
        'Kabeláž',
        'Zásuvky, vypínače a koncové přístroje',
        'Zapojení a kompletace',
        'Výchozí revize elektroinstalace',
      ],
    },
    deliveryScope: {
      included: [
        'Nosný rám KVH 60/240 mm s minerální izolací 240 mm',
        'Instalační předstěna 40 mm s minerální izolací',
        'Parotěsná rovina před nosnou konstrukcí',
        'Vnější opláštění deskami Fermacell 12,5 mm',
        'Difuzně otevřená větrotěsná fasádní membrána',
        'Svislý podkladní rošt 60/40 mm (provětrávaná mezera)',
        'Vodorovný podkladní rošt 60/40 mm pro montáž fasádních prken',
      ],
      excluded: [
        'Fasádní dřevěná prkna (např. modřín, smrk, thermo-dřevo)',
        'Spojovací nerezový materiál pro fasádní prkna',
        'Finální tmelení a nátěry interiéru',
      ],
      clientSupplied: [
        'Dřevěný fasádní obklad a jeho montáž na připravený dvojitý rošt',
        'Finální interiérové povrchové úpravy',
      ],
      deliveryNote: 'Součástí dodaného panelu nejsou finální pohledové úpravy na straně interiéru ani exteriéru. Interiér končí surovou deskou Fermacell bez finálního tmelení, stěrkování, penetrace a malby. Exteriér končí dvojitým podkladním roštem pro provětrávanou fasádu; fasádní prkna ani jejich finální povrchová úprava nejsou součástí dodávky.',
    },
    images: {
      assembledCutawayWebp: '/panels/catalog/1_2/panel_1_2_photoreal_assembled_cutaway.webp',
      explodedWebp: '/panels/catalog/1_2/panel_1_2_photoreal_exploded.webp',
      fullWebp: '/panels/catalog/1_2/panel_1_2_photoreal_full.webp',
      thumbnailWebp: '/panels/catalog/1_2/panel_1_2_thumb.webp',
      assembledCutawayPng: '/panels/catalog/1_2/panel_1_2_photoreal_assembled_cutaway.png',
      explodedPng: '/panels/catalog/1_2/panel_1_2_photoreal_exploded.png',
      reviewPng: '/panels/catalog/1_2/panel_1_2_photoreal_review.png',
    },
    layers: [
      { id: 'L01', order: 1, name: 'Sádrovláknitá deska Fermacell 12,5 mm', materialId: 'fermacell_raw', geometry: 'solid', thicknessMm: 12.5, additiveToTotal: true, explodedGroup: 0, massKgM2: 15.0, lambdaWMk: 0.32, fireClass: 'A2', function: 'Vnitřní opláštění a podklad pro finální pohledovou úpravu.' },
      { id: 'L02', order: 2, name: 'Instalační předstěna z latí 60/40 mm', materialId: 'kvh_spruce', geometry: 'frame', thicknessMm: 40.0, additiveToTotal: true, explodedGroup: 1, massKgM2: 2.0, lambdaWMk: 0.18, fireClass: 'C3', function: 'Instalační prostor pro vedení rozvodů před parotěsnou rovinou.' },
      { id: 'L03', order: 3, name: 'Minerální izolace v instalační předstěně', materialId: 'mineral_wool_soft', geometry: 'hosted_infill', hostLayerId: 'L02', thicknessMm: 40.0, additiveToTotal: false, explodedGroup: 1, massKgM2: null, lambdaWMk: 0.035, fireClass: 'A1', function: 'Vyplnění instalační dutiny pro zlepšení tepelných a akustických vlastností.' },
      { id: 'L04', order: 4, name: 'Sádrovláknitá deska Fermacell 12,5 mm', materialId: 'fermacell_raw', geometry: 'solid', thicknessMm: 12.5, additiveToTotal: true, explodedGroup: 2, massKgM2: 15.0, lambdaWMk: 0.32, fireClass: 'A2', function: 'Ztužující opláštění před nosnou konstrukcí a podklad parotěsné roviny.' },
      { id: 'L05', order: 5, name: 'Parozábrana', materialId: 'vapour_membrane', geometry: 'solid', thicknessMm: 0.5, additiveToTotal: true, explodedGroup: 3, massKgM2: 1.0, lambdaWMk: null, fireClass: null, function: 'Omezení průniku vodní páry z interiéru do nosné části panelu.' },
      { id: 'L06', order: 6, name: 'Nosný rám KVH 60/240 mm', materialId: 'kvh_spruce', geometry: 'frame', thicknessMm: 240.0, additiveToTotal: true, explodedGroup: 4, massKgM2: 10.0, lambdaWMk: 0.18, fireClass: 'C3', function: 'Hlavní nosná dřevěná konstrukce obvodového panelu.' },
      { id: 'L07', order: 7, name: 'Minerální izolace v nosném rámu', materialId: 'mineral_wool_soft', geometry: 'hosted_infill', hostLayerId: 'L06', thicknessMm: 240.0, additiveToTotal: false, explodedGroup: 4, massKgM2: null, lambdaWMk: 0.035, fireClass: 'A1', function: 'Hlavní tepelněizolační výplň mezi sloupky nosného rámu.' },
      { id: 'L08', order: 8, name: 'Sádrovláknitá deska Fermacell 12,5 mm', materialId: 'fermacell_raw', geometry: 'solid', thicknessMm: 12.5, additiveToTotal: true, explodedGroup: 5, massKgM2: 15.0, lambdaWMk: 0.32, fireClass: 'A2', function: 'Vnější ztužující opláštění nosného rámu a podklad difuzní membrány.' },
      { id: 'L09', order: 9, name: 'Difuzně otevřená fasádní membrána', materialId: 'diffusion_membrane', geometry: 'solid', thicknessMm: 0.5, additiveToTotal: true, explodedGroup: 6, massKgM2: null, lambdaWMk: null, fireClass: 'dle výrobku', function: 'Větrotěsná a vodoodpudivá ochrana vnějšího opláštění.' },
      { id: 'L10', order: 10, name: 'Svislý podkladní rošt 60/40 mm', materialId: 'kvh_spruce', geometry: 'frame', thicknessMm: 40.0, additiveToTotal: true, explodedGroup: 7, massKgM2: 2.0, lambdaWMk: 0.18, fireClass: 'C3', function: 'První rovina podkladního roštu a vymezení provětrávané mezery.' },
      { id: 'L11', order: 11, name: 'Vodorovný podkladní rošt 60/40 mm', materialId: 'kvh_spruce', geometry: 'frame', thicknessMm: 40.0, additiveToTotal: true, explodedGroup: 8, massKgM2: 2.0, lambdaWMk: 0.18, fireClass: 'C3', function: 'Druhá rovina podkladního roštu pro přímou montáž fasádního obkladu.' },
    ],
  },
  {
    id: 'wall-panel-1-3',
    code: '1.3',
    legacyCode: 'OS_VF_03',
    name: 'Ekonomický základní panel s otevřenou předstěnou',
    subtitle: 'Základní nosná konstrukce s otevřeným roštem předstěny; dokončení elektro, izolace a fasády zajišťuje klient.',
    category: 'WALL_OUTER',
    declaredThicknessMm: 225.5,
    unitPriceExVat: 6450.0,
    technicalParameters: {
      uValue: 0.22,
      rwDb: 48,
      fireResistance: 'REI 45 / DP1',
      massKgM2: 52.0,
    },
    electricalPreparation: {
      included: false,
      responsibility: 'client',
      heading: 'Elektro-přípravu a dokončení předstěny zajišťuje klient',
      description: 'Součástí dodávky je pouze otevřený dřevěný rošt instalační předstěny tloušťky 40 mm. Klient si zcela zajišťuje přípravu pro elektroinstalaci, vložení minerální izolace do předstěny a její vnitřní zaklopení deskou Fermacell včetně finální povrchové úpravy.',
      includedItems: [],
      excludedItems: [
        'Elektroinstalační chráničky a vývrty',
        'Elektroinstalační krabice',
        'Kabeláž a koncové přístroje',
        'Minerální izolace do instalační předstěny',
        'Vnitřní záklop deskou Fermacell 12,5 mm',
        'Kontaktní zateplení a fasádní systém',
      ],
    },
    deliveryScope: {
      included: [
        'Otevřený dřevěný rošt instalační předstěny 60/40 mm',
        'Sádrovláknitá deska Fermacell 12,5 mm před nosnou konstrukcí',
        'Parotěsná zábrana',
        'Nosný rám KVH 60/160 mm s minerální izolací 160 mm',
        'Vnější ztužující záklop deskou Fermacell 12,5 mm',
      ],
      excluded: [
        'Příprava elektroinstalace v předstěně',
        'Izolace instalační předstěny',
        'Vnitřní deska Fermacell',
        'Fasádní zateplení a fasádní omítka',
      ],
      clientSupplied: [
        'Veškeré rozvody elektroinstalace, chráničky a krabice',
        'Vložení minerální izolace do 40mm předstěny',
        'Montáž vnitřní desky Fermacell a její povrchová úprava',
        'Vnější kontaktní zateplení nebo provětrávaná fasáda',
      ],
      deliveryNote: 'Ekonomická varianta se na straně interiéru dodává s otevřeným 40mm roštem instalační předstěny. Minerální izolace této předstěny, vnitřní zaklopení deskou Fermacell a veškerá příprava pro elektroinstalaci nejsou součástí dodávky a zcela je zajišťuje klient. Exteriér končí surovou deskou Fermacell; kontaktní tepelná izolace, fasádní systém ani finální fasáda nejsou součástí dodávky.',
    },
    images: {
      assembledCutawayWebp: '/panels/catalog/1_3/panel_1_3_photoreal_assembled_cutaway.webp',
      explodedWebp: '/panels/catalog/1_3/panel_1_3_photoreal_exploded.webp',
      fullWebp: '/panels/catalog/1_3/panel_1_3_photoreal_full.webp',
      thumbnailWebp: '/panels/catalog/1_3/panel_1_3_thumb.webp',
      assembledCutawayPng: '/panels/catalog/1_3/panel_1_3_photoreal_assembled_cutaway.png',
      explodedPng: '/panels/catalog/1_3/panel_1_3_photoreal_exploded.png',
      reviewPng: '/panels/catalog/1_3/panel_1_3_photoreal_review.png',
    },
    layers: [
      { id: 'L01', order: 1, name: 'Instalační předstěna z latí 60/40 mm (otevřený rošt)', materialId: 'kvh_spruce', geometry: 'frame', thicknessMm: 40.0, additiveToTotal: true, explodedGroup: 0, massKgM2: 2.0, lambdaWMk: 0.18, fireClass: 'C3', function: 'Dodávaný otevřený dřevěný rošt. Elektro-přípravu, izolaci a záklop zajišťuje klient.' },
      { id: 'L02', order: 2, name: 'Sádrovláknitá deska Fermacell 12,5 mm', materialId: 'fermacell_raw', geometry: 'solid', thicknessMm: 12.5, additiveToTotal: true, explodedGroup: 1, massKgM2: 15.0, lambdaWMk: 0.32, fireClass: 'A2', function: 'Ztužující opláštění před nosnou konstrukcí a podklad parotěsné roviny.' },
      { id: 'L03', order: 3, name: 'Parozábrana', materialId: 'vapour_membrane', geometry: 'solid', thicknessMm: 0.5, additiveToTotal: true, explodedGroup: 2, massKgM2: 1.0, lambdaWMk: null, fireClass: null, function: 'Omezení průniku vodní páry z interiéru do nosné části panelu.' },
      { id: 'L04', order: 4, name: 'Nosný rám KVH 60/160 mm', materialId: 'kvh_spruce', geometry: 'frame', thicknessMm: 160.0, additiveToTotal: true, explodedGroup: 3, massKgM2: 10.0, lambdaWMk: 0.18, fireClass: 'C3', function: 'Hlavní nosná dřevěná konstrukce obvodového panelu.' },
      { id: 'L05', order: 5, name: 'Minerální izolace v nosném rámu', materialId: 'mineral_wool_soft', geometry: 'hosted_infill', hostLayerId: 'L04', thicknessMm: 160.0, additiveToTotal: false, explodedGroup: 3, massKgM2: null, lambdaWMk: 0.035, fireClass: 'A1', function: 'Hlavní tepelněizolační výplň mezi sloupky nosného rámu.' },
      { id: 'L06', order: 6, name: 'Sádrovláknitá deska Fermacell 12,5 mm', materialId: 'fermacell_raw', geometry: 'solid', thicknessMm: 12.5, additiveToTotal: true, explodedGroup: 4, massKgM2: 15.0, lambdaWMk: 0.32, fireClass: 'A2', function: 'Vnější ztužující opláštění a dodávaný vnější povrch panelu bez fasády.' },
    ],
  },
  {
    id: 'wall-panel-1-4',
    code: '1.4',
    name: 'CLT masivní panel 84 mm, jednostranně pohledový',
    subtitle: 'Třívrstvý křížem lepený masivní dřevěný panel s vyfrézovanými elektro-trasami přímo v těle masivu.',
    category: 'WALL_OUTER',
    declaredThicknessMm: 84.0,
    unitPriceExVat: 9200.0,
    technicalParameters: {
      uValue: 1.15,
      rwDb: 34,
      fireResistance: 'REI 60 / DP1',
      massKgM2: 41.2,
    },
    electricalPreparation: {
      included: true,
      responsibility: 'supplier',
      heading: 'Elektroinstalační příprava je vyfrézována v CLT panelu',
      description: 'Panel nemá montážní předstěnu. Elektroinstalační trasy jsou proto připraveny přímo v masivním CLT jako projektově určené vývrty osazené chráničkami. Součástí dodávky jsou rovněž vývrty pro následnou montáž elektroinstalačních krabic.',
      includedItems: [
        'Projektově určené CNC vývrty přímo v masivním CLT panelu',
        'Elektroinstalační chráničky vložené do vývrtů pro vedení kabeláže',
        'Vývrty pro následnou montáž elektroinstalačních krabic',
      ],
      excludedItems: [
        'Elektroinstalační krabice',
        'Kabeláž',
        'Koncové přístroje (zásuvky, vypínače)',
        'Zapojení a revize',
      ],
    },
    deliveryScope: {
      included: [
        'Masivní třívrstvý CLT panel tloušťky 84 mm (lamely 28/28/28 mm)',
        'Interiérová strana v pohledové kvalitě (VI) – celistvá plocha bez viditelných spár',
        'Projektově připravené svislé elektro-trasy s chráničkami a vývrty pro krabice',
        'Exteriérová strana v nepohledové kvalitě (NVI)',
      ],
      excluded: [
        'Dodatečný interiérový nátěr nebo lazura (není-li sjednáno)',
        'Vnější tepelná izolace, větrotěsná vrstva a fasádní obklad',
      ],
      clientSupplied: [
        'Vnější obálka stavby (zateplení, rošt, fasáda)',
        'Dokončení elektroinstalace (kabely, přístroje)',
      ],
      deliveryNote: 'Dodávku tvoří samotný masivní CLT panel tloušťky 84 mm s projektově připravenými elektroinstalačními vývrty osazenými chráničkami pro vedení elektroinstalace a s vývrty pro následnou montáž elektroinstalačních krabic. Interiérová strana je dodávána v pohledové kvalitě. Exteriérová strana je nepohledová a určená pro následné doplnění obálky stavby.',
    },
    images: {
      assembledCutawayWebp: '/panels/catalog/1_4/panel_1_4_photoreal_assembled_cutaway.webp',
      explodedWebp: '/panels/catalog/1_4/panel_1_4_photoreal_exploded.webp',
      fullWebp: '/panels/catalog/1_4/panel_1_4_photoreal_full.webp',
      thumbnailWebp: '/panels/catalog/1_4/panel_1_4_thumb.webp',
      assembledCutawayPng: '/panels/catalog/1_4/panel_1_4_photoreal_assembled_cutaway.png',
      explodedPng: '/panels/catalog/1_4/panel_1_4_photoreal_exploded.png',
      reviewPng: '/panels/catalog/1_4/panel_1_4_photoreal_review.png',
    },
    layers: [
      {
        id: 'L01',
        order: 1,
        name: 'Masivní třívrstvý CLT panel 84 mm',
        materialId: 'clt_spruce_visual',
        geometry: 'clt_panel',
        thicknessMm: 84.0,
        additiveToTotal: true,
        explodedGroup: 0,
        massKgM2: 41.2,
        lambdaWMk: 0.12,
        fireClass: 'D-s2, d0',
        function: 'Nosná a ztužující obvodová stěna; vnitřní krycí vrstva současně vytváří přiznaný pohledový povrch. Projektově určené vývrty s chráničkami a vývrty pro krabice vytvářejí přípravu elektroinstalace přímo v masivním panelu.',
        lamellae: [
          { id: 'L01-A', name: 'Vnitřní krycí lamela – pohledová (VI)', thicknessMm: 28.0, grainDirection: 'vertical_z', surfaceQuality: 'VI', materialId: 'clt_spruce_visual' },
          { id: 'L01-B', name: 'Střední příčná lamela (NVI)', thicknessMm: 28.0, grainDirection: 'horizontal_x', surfaceQuality: 'NVI', materialId: 'clt_spruce_transverse' },
          { id: 'L01-C', name: 'Vnější krycí lamela – nepohledová (NVI)', thicknessMm: 28.0, grainDirection: 'vertical_z', surfaceQuality: 'NVI', materialId: 'clt_spruce_nonvisual' },
        ],
      },
    ],
  },
];
